# frozen_string_literal: true

source "https://rubygems.org"

gem "activerecord-jdbcsqlite3-adapter", platform: :jruby
gem "non-digest-assets", path: "../.."
gem "rails", "~> 6.0.0"
gem "sqlite3", platform: :ruby
